### ISSUE TITLE
Improve code completion

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#155]
## To do
- [x] Add completion for 'conditionRef' in Pipeline conditions https://github.com/redhat-developer/intellij-tekton/issues/151
- [x] RunAfter code completion should list tasks in the current pipeline https://github.com/redhat-developer/intellij-tekton/issues/152
- [x] taskRef code completion should list tasks in current cluster https://github.com/redhat-developer/intellij-tekton/issues/153
- [x] Add code completion to list all params/resources/workspaces/results in pipeline/task steps  https://github.com/redhat-developer/intellij-tekton/issues/154
- [x] Resource code completion should list input resources in pipeline https://github.com/redhat-developer/intellij-tekton/issues/189
- [x] Remove general snippets from other code completion suggestions https://github.com/redhat-developer/intellij-tekton/issues/191
- [x] Add code completion for single inputs (params, workspaces, resources) https://github.com/redhat-developer/intellij-tekton/issues/193
- [x] Add code completion for when clause https://github.com/redhat-developer/intellij-tekton/issues/209
- [x] Add default value with taskRef code completion https://github.com/redhat-developer/intellij-tekton/issues/226
